"""create initial tables

Revision ID: 05a242de7da2
Revises: 
Create Date: 2026-06-10 11:33:38.587292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05a242de7da2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_level_streams',
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('stream_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('stream_id'),
    sa.UniqueConstraint('stream_name')
    )
    op.create_index(op.f('ix_a_level_streams_stream_id'), 'a_level_streams', ['stream_id'], unique=False)
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('districts',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=80), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('district_id'),
    sa.UniqueConstraint('district_name')
    )
    op.create_index(op.f('ix_districts_district_id'), 'districts', ['district_id'], unique=False)
    op.create_table('fields_of_interest',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('field_id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_index(op.f('ix_fields_of_interest_field_id'), 'fields_of_interest', ['field_id'], unique=False)
    op.create_table('universities',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('logo_image_path', sa.Text(), nullable=True),
    sa.Column('ugc_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('university_id')
    )
    op.create_index(op.f('ix_universities_university_id'), 'universities', ['university_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('academic_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('z_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['a_level_streams.stream_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_admin_audit_logs_log_id'), 'admin_audit_logs', ['log_id'], unique=False)
    op.create_table('degree_programs',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=200), nullable=False),
    sa.Column('duration_years', sa.SmallInteger(), nullable=False),
    sa.Column('syllabus_summary', sa.Text(), nullable=True),
    sa.Column('job_demand_score', sa.SmallInteger(), nullable=True),
    sa.Column('ugc_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['a_level_streams.stream_id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.university_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_index(op.f('ix_degree_programs_program_id'), 'degree_programs', ['program_id'], unique=False)
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['a_level_streams.stream_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.create_table('university_stages',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.university_id'], ),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_index(op.f('ix_university_stages_stage_id'), 'university_stages', ['stage_id'], unique=False)
    op.create_table('uploaded_pdfs',
    sa.Column('pdf_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('pdf_id')
    )
    op.create_table('cutoff_marks',
    sa.Column('cutoff_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('min_cutoff_mark', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['degree_programs.program_id'], ),
    sa.PrimaryKeyConstraint('cutoff_id')
    )
    op.create_index(op.f('ix_cutoff_marks_cutoff_id'), 'cutoff_marks', ['cutoff_id'], unique=False)
    op.create_table('ocr_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('pdf_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_id'], ['uploaded_pdfs.pdf_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('profile_interests',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields_of_interest.field_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['academic_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'field_id')
    )
    op.create_table('profile_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('slot_position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['academic_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_subjects_id'), 'profile_subjects', ['id'], unique=False)
    op.create_table('program_careers',
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['degree_programs.program_id'], ),
    sa.PrimaryKeyConstraint('career_id')
    )
    op.create_index(op.f('ix_program_careers_career_id'), 'program_careers', ['career_id'], unique=False)
    op.create_table('program_courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('year_level', sa.SmallInteger(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['degree_programs.program_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_program_courses_course_id'), 'program_courses', ['course_id'], unique=False)
    op.create_table('specializations',
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('spec_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['degree_programs.program_id'], ),
    sa.PrimaryKeyConstraint('spec_id')
    )
    op.create_index(op.f('ix_specializations_spec_id'), 'specializations', ['spec_id'], unique=False)
    op.create_table('ocr_extracted_rows',
    sa.Column('row_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('university_name', sa.Text(), nullable=False),
    sa.Column('program_name', sa.Text(), nullable=False),
    sa.Column('district_name', sa.String(length=80), nullable=False),
    sa.Column('cutoff_mark', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ocr_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index(op.f('ix_ocr_extracted_rows_row_id'), 'ocr_extracted_rows', ['row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_extracted_rows_row_id'), table_name='ocr_extracted_rows')
    op.drop_table('ocr_extracted_rows')
    op.drop_index(op.f('ix_specializations_spec_id'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_program_courses_course_id'), table_name='program_courses')
    op.drop_table('program_courses')
    op.drop_index(op.f('ix_program_careers_career_id'), table_name='program_careers')
    op.drop_table('program_careers')
    op.drop_index(op.f('ix_profile_subjects_id'), table_name='profile_subjects')
    op.drop_table('profile_subjects')
    op.drop_table('profile_interests')
    op.drop_table('ocr_jobs')
    op.drop_index(op.f('ix_cutoff_marks_cutoff_id'), table_name='cutoff_marks')
    op.drop_table('cutoff_marks')
    op.drop_table('uploaded_pdfs')
    op.drop_index(op.f('ix_university_stages_stage_id'), table_name='university_stages')
    op.drop_table('university_stages')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_degree_programs_program_id'), table_name='degree_programs')
    op.drop_table('degree_programs')
    op.drop_index(op.f('ix_admin_audit_logs_log_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_table('academic_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_university_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_fields_of_interest_field_id'), table_name='fields_of_interest')
    op.drop_table('fields_of_interest')
    op.drop_index(op.f('ix_districts_district_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('admins')
    op.drop_index(op.f('ix_a_level_streams_stream_id'), table_name='a_level_streams')
    op.drop_table('a_level_streams')
    # ### end Alembic commands ###
