"""add program fields table

Revision ID: 082df0903ea4
Revises: dd9d4dce9658
Create Date: 2026-06-10 17:46:17.273142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082df0903ea4'
down_revision: Union[str, Sequence[str], None] = 'dd9d4dce9658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_fields',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields_of_interest.field_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['degree_programs.program_id'], ),
    sa.PrimaryKeyConstraint('program_id', 'field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_fields')
    # ### end Alembic commands ###
